# NOTE: Generated By HttpRunner v3.1.4
# FROM: .\test_case.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestCase(HttpRunner):

    config = Config("basic test config").base_url("http://127.0.0.1:8000/api")

    teststeps = [
        Step(
            RunRequest(" test_add_event_all_null")
            .post("/add_event/")
            .with_data({"eid": "", "limit": "", "address": "", "start_time": ""})
            .validate()
            .assert_equal("body.status", 10021)
            .assert_equal("body.message", "parameter error")
        ),
        Step(
            RunRequest(" test_add_event_eid_exist")
            .post("/add_event/")
            .with_data(
                {
                    "eid": 1,
                    "name": "oneplus",
                    "limit": 2000,
                    "address": "shenzhen",
                    "start_time": "2017",
                }
            )
            .validate()
            .assert_equal("body.status", 10022)
            .assert_equal("body.message", "event id already exists")
        ),
        Step(
            RunRequest(" test_add_event_success")
            .post("/add_event/")
            .with_data(
                {
                    "eid": 25,
                    "name": "oneplus9",
                    "limit": 2000,
                    "address": "shenzhen",
                    "start_time": "2017-05-10 12:00:00",
                }
            )
            .validate()
            .assert_equal("body.status", 10200)
            .assert_equal("body.message", "add event success")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestCase().test_start()
