# Generated by Django 2.1.7 on 2019-03-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-id']},
        ),
    ]
